apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-settings
data:
  config.php : |
    <?php
    $CONFIG = array (
      'htaccess.RewriteBase' => '/',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'apps_paths' => 
      array (
        0 => 
        array (
          'path' => '/var/www/html/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 => 
        array (
          'path' => '/var/www/html/custom_apps',
          'url' => '/custom_apps',
          'writable' => true,
        ),
      ),
      'upgrade.disable-web' => true,
      'instanceid' => 'oco7r43z3ek3',
      'passwordsalt' => 'R9NJ1/bFxygeMgV4OQ/u2L+O2lvMYO',
      'secret' => 'MHBQxLqAge4j4yjA/Yxc+7h4BrmyqqAp9QUm8qAZUg55TU3C',
      'trusted_domains' => *
      array (
        0 => 'localhost:32162',
        1 => '*',
      ),
      'datadirectory' => '/var/www/html/data',
      'dbtype' => 'sqlite3',
      'version' => '30.0.4.1',
      'overwrite.cli.url' => 'http://localhost:32162',
      'installed' => true,
      'config_is_read_only' => false,
    );
    ?>
